from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='books.index'),
    path('list_books/', views.list_books, name='books.list_books'),
    path('one_book/', views.one_book, name='books.one_book'),
    path('aboutus/', views.aboutus, name='books.aboutus'),
    path('html5/links/', views.links),
    path('html5/text/formatting/', views.formatting),
    path('html5/listing/', views.listing),
    path('html5/tables/', views.tables),
    path('search/', views.search, name="books.search"),
    path('simple/query/', views.simple_query, name='books.simple_query'),
    path('complex/query/', views.complex_query, name='books.complex_query'),
    path('lab8/task1/', views.lab8_task1, name='lab8_task1'),
    path('lab8/task2/', views.lab8_task2, name='lab8_task2'),
    path('lab8/task3/', views.lab8_task3, name='lab8_task3'),
    path('lab8/task4/', views.lab8_task4, name='lab8_task4'),
    path('lab8/task5/', views.lab8_task5, name='lab8_task5'),
    path('lab8/task7/', views.lab8_task7, name='lab8_task7'),
    path('lab9/task1/', views.lab9_task1, name='lab9_task1'),
    path('lab9/task2/', views.lab9_task2, name='lab9_task2'),
    path('lab9/task3/', views.lab9_task3, name='lab9_task3'),
    path('lab9/task4/', views.lab9_task4, name='lab9_task4'),
    path('lab9/task5/', views.lab9_task5, name='lab9_task5'),
    path('lab9/task6/', views.lab9_task6, name='lab9_task6'),
    path('lab9_part1/listbooks', views.lab10_listbooks, name='lab10_listbooks'),
    path('lab9_part1/addbook', views.lab10_addbook, name='lab10_addbook'),
    path('lab9_part1/editbook/<int:id>', views.lab10_editbook, name='lab10_editbook'),
    path('lab9_part1/deletebook/<int:id>', views.lab10_deletebook, name='lab10_deletebook'),
    path('lab9_part2/listbooks', views.lab10_listbooks_form, name='lab10_listbooks_form'),
    path('lab9_part2/addbook', views.lab10_addbook_form, name='lab10_addbook_form'),
    path('lab9_part2/editbook/<int:id>', views.lab10_editbook_form, name='lab10_editbook_form'),
    path('lab9_part2/deletebook/<int:id>', views.lab10_deletebook_form, name='lab10_deletebook_form'),
]