# Generated by Django 6.0.2 on 2026-04-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.SmallIntegerField(default=1),
        ),
    ]
